title: Default
columns:
  - width: 2/3
    sections:
      content:
        extends: sections/content
  - width: 1/3
    sections:
      images:
        headline: Images
        type: files
        layout: cards
        text: false
        info: "{{ file.caption.kt }}"
        image:
          cover: true
          ratio: 1/1
